import { z } from "zod";

export const RoadsterSchema = z.object({
  apoapsis_au: z.number(),
  details: z.string(),
  earth_distance_km: z.number(),
  earth_distance_mi: z.number(),
  eccentricity: z.number(),
  epoch_jd: z.number(),
  flickr_images: z.array(z.string().url()),
  id: z.string(),
  inclination: z.number(),
  launch_date_unix: z.number(),
  launch_date_utc: z.string().datetime(),
  launch_mass_kg: z.number(),
  launch_mass_lbs: z.number(),
  longitude: z.number(),
  mars_distance_km: z.number(),
  mars_distance_mi: z.number(),
  name: z.string(),
  norad_id: z.number(),
  orbit_type: z.string(),
  periapsis_arg: z.number(),
  periapsis_au: z.number(),
  period_days: z.number(),
  semi_major_axis_au: z.number(),
  speed_kph: z.number(),
  speed_mph: z.number(),
  video: z.string().url(),
  wikipedia: z.string().url(),
});
